pub(crate) fn help_text() -> String {
    public_help_text()
}

pub(crate) fn public_help_text() -> String {
    [
        "arb-runtime",
        "中文说明：对外只保留两个运行模式。默认 7*24 小时监控全部交易所、全市场、全策略。",
        "",
        "Modes:",
        "  live   正式实盘：全交易所、全市场、全策略监控，满足门禁时真实下单",
        "  paper  测试盘：全交易所、全市场、全策略监控，满足门禁时只做模拟下单",
        "",
        "Read-only utility:",
        "  portfolio-dashboard [--bind 127.0.0.1:8805] [--resident-root dir] [--navigation-wss-pid-file file] [--once]",
        "        启动只读组合余额、仓位、导航和错误日志 JSON API；不签名、不下单、不撤单、不转账",
        "",
        "Common options:",
        "  --config path                 配置文件，默认 templates/personal_guarded_live.preflight.yaml",
        "  --out dir                     输出目录；live 默认 target/arb-runtime/live，paper 默认 target/arb-runtime/paper",
        "  --interval-secs n             监控轮询间隔，默认 5",
        "  --min-net-bps n               最小净收益门槛，默认 5",
        "Live-only option:",
        "  --i-understand-live-orders    正式实盘必须显式提供；表示接受真实下单风险",
        "",
        "Examples:",
        "  target/debug/arb-runtime paper",
        "  target/debug/arb-runtime live --i-understand-live-orders",
        "",
        "内部调试命令默认关闭；portfolio-dashboard 是只读 JSON API，不需要启用内部调试命令。",
    ]
    .join("\n")
}

#[allow(dead_code)]
pub(crate) fn legacy_help_text() -> String {
    [
        "arb-runtime",
        "中文说明：默认只运行离线、模拟、可回放的运行时装配；实盘分发命令需要 live-exec 构建和显式确认。",
        "中文说明：fixture_root 可使用仓库根目录相对路径，例如 fixtures/replay/full_pipeline_simulated。",
        "",
        "Commands:",
        "  replay [fixture_root] [--accept]  Run S9-01 full pipeline and compare golden outputs",
        "  health [fixture_root]             Run S9-02 startup and health checks only",
        "  health-config <config_path>       Run startup checks against a local config file",
        "  live-market-sim [fixture_root] [--symbol BTCUSDT] [--out dir]",
        "                                    Fetch one public market-data snapshot and run simulated execution",
        "  binance-basis-scan [--symbol BTCUSDT] [--out dir]",
        "                                    Fetch Binance public spot/perp data and run read-only basis strategy",
        "  binance-basis-pipeline [--symbol BTCUSDT] [--out dir]",
        "                                    Fetch Binance public spot/perp data and run simulated pipeline artifacts",
        "  bybit-basis-scan [--symbol BTCUSDT] [--out dir]",
        "                                    Fetch Bybit public spot/linear-perp data and run read-only basis strategy",
        "  bybit-basis-pipeline [--symbol BTCUSDT] [--out dir]",
        "                                    Fetch Bybit public spot/linear-perp data and run simulated pipeline artifacts",
        "  binance-guarded-live-preview [--market-artifacts dir] [--out dir] [--decision approve|reject --expected-plan-hash hash --approval-event-id id --reviewer id --decided-at ts --expires-at ts --reason text]",
        "                                    Generate Binance BTCUSDT GuardedLivePersonal plan preview, plan hash, and manual confirmation audit material",
        "  binance-guarded-live-gate-release-preview [--preview-dir dir] [--out dir]",
        "                                    Consume Approved manual record and generate a non-dispatching manual gate release fact preview",
        "  binance-guarded-live-pre-dispatch-dry-run [--preview-dir dir] [--config path] [--out dir]",
        "                                    Run fail-closed pre-dispatch dry run after manual gate release preview",
        "  binance-guarded-live-dispatch [--preview-dir dir] [--config path] [--out dir] --i-understand-live-orders",
        "                                    live-exec only: submit the approved GuardedLive BTCUSDT order and query private confirmation",
        "  binance-basis-live-stack [--symbol BTCUSDT] [--config path] [--out dir] [--spot-wss-bind 127.0.0.1:8801 --perp-wss-bind 127.0.0.1:8802] [--monitor-symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--readiness-timeout-secs 60] [--interval-secs 60] [--min-net-bps 5] [--auto-price-guard-bps 2] [--max-concurrent-positions n --max-total-notional-usdt amount] [--use-existing-monitors] [--execute-live --i-understand-basis-live-orders]",
        "                                    Supervisor: launch Binance spot/perp WSS monitors scoped to --symbol by default, verify readiness, run resident live runner, and record stack logs/events/summary under one RUN_ROOT",
        "  binance-basis-resident-live [--symbol BTCUSDT] [--config path] [--out dir] [--interval-secs 60] [--min-net-bps 5] [--auto-price-guard-bps 2] [--spot-wss-monitor-url url --perp-wss-monitor-url url] [--private-order-events-dir dir] [--adl-events-dir dir] [--position-state file] [--max-cycles n] [--max-concurrent-positions n --max-total-notional-usdt amount] [--execute-live --i-understand-basis-live-orders]",
        "                                    Binance basis resident runner: supervise open positions, keep opening new entries when capacity allows, and stop on lock, STOP file, unknown state, or risk caps",
        "  multi-venue-basis-resident-live [--venues binance,bybit,okx,bitget] [--config path] [--out dir] [--interval-secs 60] [--min-net-bps 5] [--auto-price-guard-bps 2] [--max-concurrent-positions n --max-total-notional-usdt amount] [--<venue>-opportunities-url url] [--<venue>-spot-wss-monitor-url url --<venue>-perp-wss-monitor-url url] [--execute-live --i-understand-basis-live-orders]",
        "                                    Multi-venue resident runner: use guarded entry per venue, enforce risk caps, and halt fail-closed on unknown live state",
        "  multi-venue-basis-live-stack [--venues binance,bybit,okx,bitget] [--config path] [--out dir] [--monitor-symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--readiness-timeout-secs 60] [--interval-secs 60] [--max-concurrent-positions n --max-total-notional-usdt amount] [--use-existing-monitors] [--execute-live --i-understand-basis-live-orders]",
        "                                    Supervisor: launch managed Binance/Bybit/OKX/Bitget WSS monitors scoped to venue symbols by default; opportunity URLs keep all-market scope unless --monitor-symbol is set",
        "  resolve-live-wss-symbols [--strategies list] [--monitors list] [--format shell|json]",
        "                                    Resolve live WSS symbol scopes from public venue spot/perp and cross-venue perp availability; read-only and intended for start-arb-runtime-live.sh auto scope",
        "  binance-wss-book-ticker [--bind 127.0.0.1:8801] [--symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--market spot|usdm-perp] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run Binance public WSS bookTicker scoped/all-market monitor and serve /api/binance-wss-book-ticker/status",
        "  bybit-wss-book-ticker [--bind 127.0.0.1:8802] [--symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--market spot|linear-perp] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run Bybit public WSS orderbook.1 scoped/all-market monitor and serve /api/bybit-wss-book-ticker/status",
        "  okx-wss-book-ticker [--bind 127.0.0.1:8807] [--symbol ALL_USDT|BTC-USDT[,ETH-USDT]] [--market spot|swap] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run OKX public WSS tickers scoped/all-market monitor and serve /api/okx-wss-book-ticker/status",
        "  bitget-wss-book-ticker [--bind 127.0.0.1:8809] [--symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--market spot|usdt-futures] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run Bitget public WSS ticker scoped/all-market monitor and serve /api/bitget-wss-book-ticker/status",
        "  aster-wss-book-ticker [--bind 127.0.0.1:8794] [--symbol ALL_USDT|BTCUSDT[,ETHUSDT]] [--market usdt-futures] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run Aster public WSS bookTicker scoped/all-market monitor and serve /api/aster-wss-book-ticker/status",
        "  hyperliquid-wss-book-ticker [--bind 127.0.0.1:8795] [--symbol ALL_USDT|BTC[,ETH]] [--market perp] [--reconnect-delay-secs 2] [--once --updates 3]",
        "                                    Run Hyperliquid public WSS top-of-book scoped/all-market monitor and serve /api/hyperliquid-wss-book-ticker/status",
        "  binance-basis-monitor [--bind 127.0.0.1:8796] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--once] [--out dir]",
        "                                    Monitor all Binance public USDT spot/perp basis rows and serve /api/basis/status",
        "  basis-exit-supervisor --position-state file [--config file] [--spot-wss-monitor-url url] [--perp-wss-monitor-url url] [--adl-events-dir dir] [--once] [--execute-live --i-understand-basis-live-orders] [--out dir]",
        "                                    Supervise an opened spot-perp basis position and trigger close/de-risk actions",
        "  bybit-basis-monitor [--bind 127.0.0.1:8797] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--once] [--out dir]",
        "                                    Monitor all Bybit public USDT spot/perp basis rows and serve /api/bybit-basis/status",
        "  okx-basis-monitor [--bind 127.0.0.1:8798] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--once] [--out dir]",
        "                                    Monitor all OKX public USDT spot/perp basis rows and serve /api/okx-basis/status",
        "  bitget-basis-monitor [--bind 127.0.0.1:8803] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--once] [--out dir]",
        "                                    Monitor all Bitget public USDT spot/USDT-FUTURES basis rows and serve /api/bitget-basis/status",
        "  hyperliquid-basis-monitor [--bind 127.0.0.1:8799] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--perp-wss-monitor-url url] [--once] [--out dir]",
        "                                    Monitor all Hyperliquid public USDC spot/perp basis rows, optionally overriding perp top-of-book from WSS, and serve /api/hyperliquid-basis/status",
        "  aster-basis-monitor [--bind 127.0.0.1:8800] [--interval-secs 5] [--min-abs-funding-rate 0] [--min-net-bps 5] [--perp-wss-monitor-url url] [--once] [--out dir]",
        "                                    Monitor all Aster public USDT spot/perp basis rows, optionally overriding perp top-of-book from WSS, and serve /api/aster-basis/status",
        "  funding-arb-monitor [--bind 127.0.0.1:8804] [--interval-secs 5] [--clear-sources --source venue=url] [--min-net-funding-bps 5] [--execution-reports file] [--resident-events file] [--opportunity-history file] [--once] [--out dir]",
        "                                    Aggregate local basis monitor status snapshots into cross-exchange funding arb opportunities and optionally expose guarded dispatch gate reports",
        "  portfolio-dashboard [--bind 127.0.0.1:8805] [--account-snapshot file | --account-raw-snapshot file] [--position-snapshot file | --position-raw-snapshot file | --resident-root dir] [--funding-snapshot file] [--navigation-wss-pid-file file] [--once]",
        "                                    Serve read-only JSON APIs for exchange balances, positions, navigation, and error logs from local snapshots; no signing, orders, cancels, or transfers",
        "  wallet-signer-preflight [--aster-signer 0x...] [--aster-signer-cmd-env env] [--skip-aster] [--check-hyperliquid [--hyperliquid-agent 0x...] --hyperliquid-source a|b] [--out dir]",
        "                                    Run local signer and address-match checks before private read-only or live signing; no exchange requests and no mutable execution",
        "  funding-arb-private-readonly-snapshot-once --snapshot file --pair-id id [--config file] [--funding-settlement-raw-snapshot file] [--hyperliquid-user 0x...] [--aster-user 0x...] [--aster-signer 0x...] [--aster-signer-cmd-env env] [--out dir]",
        "                                    Fetch read-only private account/position/funding settlement raw snapshots for a funding arb pair; Aster auto-uses arb-wallet-signer unless the signer command env override is set; no orders, cancels, transfers, or mutable execution",
        "  portfolio-private-readonly-snapshot [--config file] [--venue venue] [--interval-secs 60] [--once] [--hyperliquid-user 0x...] [--aster-user 0x...] [--aster-signer 0x...] [--aster-signer-cmd-env env] [--out dir]",
        "                                    Fetch all configured exchange account and position raw snapshots on a timer for portfolio-dashboard; no orders, cancels, transfers, or mutable execution",
        "  funding-arb-guarded-dry-run-once --snapshot file --pair-id id [--config file] [--funding-settlement-raw-snapshot file] [--private-account-snapshot file | --private-account-raw-snapshot file] [--private-position-snapshot file | --private-position-raw-snapshot file] [--private-execution-snapshot file] [--out dir] [--min-net-funding-bps 5]",
        "                                    Build a non-dispatching guarded dry-run report from one funding arb observer candidate",
        "  funding-arb-guarded-live-canary-once --snapshot file --pair-id id [dry-run snapshot options] [--private-order-events-dir dir] [--aster-user 0x...] [--aster-signer 0x...] [--hyperliquid-user 0x...] [--hyperliquid-source a|b] [--hyperliquid-asset-id BTCUSDT=0] [--execute-live --i-understand-funding-arb-live-orders]",
        "                                    Build a guarded funding-arb canary plan and, only with explicit live flags, submit/confirm the Aster USDT-settled and Hyperliquid USDC-settled perp legs; Hyperliquid asset id auto-resolves unless overridden",
        "  funding-arb-resident-live [--snapshot file | --source venue=url] [--pair-id id] [--config file] [--funding-settlement-raw-snapshot file] [--private-order-events-dir dir] [--interval-secs 60] [--max-cycles n] [--hyperliquid-user 0x...] [--hyperliquid-source a|b] [--hyperliquid-asset-id BTCUSDT=0] [--aster-user 0x...] [--aster-signer 0x...] [--execute-live --i-understand-funding-arb-live-orders] [--allow-unknown-recovery] [--disable-auto-residual-de-risk] [--exit-only]",
        "                                    Resident funding-arb scanner: refresh private read-only snapshots, run guarded entry cycles, register live positions, and supervise reduce-only exit/de-risk; Aster defaults to USDT and Hyperliquid defaults to USDC",
        "  opportunity-recorder [--root dir] [--source venue=url] [--funding-arb-url url] [--strategies list] [--interval-secs 5] [--once]",
        "                                    Resident observer recorder implemented in Rust: poll local opportunity APIs and write JSONL/health logs without per-poll curl+jq subprocesses",
    ]
    .join("\n")
}
